version: "1.0"
info:
  model: int-scaffold
packages:
- name: Riba_1007Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: rimaSCName
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: rimabarman
  gitBranch: main
- name: WmSalesforceRESTProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
services:
- serviceName: project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_1_Rima
  packages:
  - name: Riba_1007Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.198
- serviceName: project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: Riba_1007Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.198
- serviceName: project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:TestDB
  packages:
  - name: Riba_1007Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.198
- serviceName: project.riba_1007.WmSalesforceRESTProvider.com_softwareag_cloudstreams_salesforce_rest_v60.connections:RestConnAlias
  packages:
  - name: Riba_1007Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.198
- serviceName: project.riba_1007.integrations:AlertsCRTandERT
  packages:
  - name: Riba_1007Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.198
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2106
- serviceName: project.riba_1007.integrations:Copy_deepclonetest
  packages:
  - name: Riba_1007Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.198
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2106
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2106
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2106
- serviceName: project.riba_1007.integrations:SIQAAdapterFlow
  packages:
  - name: Riba_1007Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.198
- serviceName: project.riba_1007.integrations:Test_RestConnector
  packages:
  - name: Riba_1007Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.198
- serviceName: project.riba_1007.integrations:deepclonetest
  packages:
  - name: Riba_1007Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.198
configurationVariables:
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.serverName
  : 9.46.196.248
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.socketLinger
  : "-1"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.databaseName
  : MYSQL_DATABASE
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionEnabled
  : "false"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.readTimeout
  : "30000"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.oauth_v20.authorizationServerUrl
  : https://login.salesforce.com/services/oauth2/authorize
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.networkProtocol
  : tcp
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionManagerSettings.poolable
  : "false"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.timeoutType
  : auto
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.portNumber
  : "3306"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionManagerSettings.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.providerUrl
  : https://d0o000001qr6keac-dev-ed.my.salesforce.com
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.transactionType
  : NO_TRANSACTION
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.enableSNI
  : "true"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.driverType
  : TestDrv
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.oauth_v20.scope
  : offline_access api refresh_token
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.oauth_v20.authenticationServerUrl
  : https://login.salesforce.com/services/oauth2/token
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.oauth_v20.refreshAccessToken
  : "true"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.oauth.accessToken
  : "{AES}bzO+KX5xKoE0CKrgiYZryDr8htPRGuUMY3q4TndvSIQ6E3Hih2GI/xLe8CAGMBhBc5ZOWvNUI+3pwbsAg1sNfIBX4BHDEwKsjJ9XzOKnpS1oSsZMHmkNTnWajawBLOChHhYVaKBE7rCdHk1MTHVOXWmK1wuN3U1rA1B0VhuZoUw="
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.dbType
  : MySQL
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.minimumPoolSize
  : "1"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionManagerSettings.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.oauth_v20.accessTokenRefreshURLRequest
  : URL Query String
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.validateAfterInactivity
  : "1000"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionManagerSettings.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.oauth.consumerSecret
  : "{AES}H3DUtu7FPRrFm9VYcSfJnS3lCjio/Y0dcYLG0xJfNKLdKR+a9WILwQTFauAGCQLJq9tT9MRnltJ6j2bw1Uxhv2mK1wuN3U1rA1B0VhuZoUw="
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.trustStore
  : ""
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.maximumPoolSize
  : "10"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.retryCount
  : "4"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.keyStore
  : ""
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.user
  : siqatest
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionManagerSettings.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.oauth_v20.refreshToken
  : "{AES}iVEYOEICT1x7P9RL3dwVv0pQv1IODTw0Qm0vrSHPR8I0XZ0/KrBE7WODHo6AzR166idpzFEQfoTJmt6zt5fHZeFTx2dZghOC8L11eRCny+ESS68TtmHmF1U8vQb/ALWK"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.oauth_v20.authorizationHeaderPrefix
  : Bearer
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.oauth_v20.accessTokenRefreshURL
  : https://d0o000001qr6keac-dev-ed.my.salesforce.com/services/oauth2/token
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.oauth_v20.authorizationHeaderInTokenRefresh
  : "false"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.retryIfRequestSentOk
  : "true"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.password
  : "{AES}D6/2AGfsSWDOcWCLrORnEQ=="
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.reuseAddr
  : "false"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionManagerSettings.heartBeatInterval
  : "0"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cx.grant_type
  : refresh_token
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.oauth.consumerId
  : 3MVG9pe2TCoA1Pf6F9PMP1LEDshTltGOTU2s4Xe3IzQbW5IIn21uWb9hkEKoAPPs0jyz1LQxPZlHx8Rh0WIlr
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.sockBuffSize
  : "8192"
  ? artConnection.Riba_1007Project.project.riba_1007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1_Rima.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.connectTimeout
  : "30000"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..riba_1007..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:RestConnAlias.poolable
  : "true"
